### ISSUE TITLE
KjException: failed: miniposix::read(fd, pos, max - pos): Bad file descriptor;

### ISSUE THREAD

**Issue by ejhumphrey** [jparyani/pycapnp#82] opened 2015-08-30 15:27 UTC
Attempts to read large integer lists (thousands of elements) are causing a KjException via the pycapnp library, but parse fine in C++. Not sure what's going wrong, and hoping the example repository I threw together can help troubleshoot the issue. Entirely possible I'm doing something incorrectly, but this seemed like the place to start since the exception is getting thrown in Python:

https://github.com/ejhumphrey/capn-demo

Any help would be greatly appreciated!

```
Traceback (most recent call last):
  File "test_pycapnp.py", line 26, in <module>
    test_reading(args.num_elements)
  File "test_pycapnp.py", line 16, in test_reading
    np.asarray(x.values, dtype=DTYPE),
  File "capnp/lib/capnp.pyx", line 1022, in capnp.lib.capnp._DynamicStructReader.__getattr__ (capnp/lib/capnp.cpp:22190)
capnp.lib.capnp.KjException: src/kj/io.c++:259: failed: miniposix::read(fd, pos, max - pos): Bad file descriptor; fd = 3
stack: 0x1060d1850 0x1060d5379 0x1060d7a0b 0x1060d70ea 0x1060d67cf 0x1060d65f5 0x10602129c 0x1060d64b1 0x106020329 0x10600b751 0x1060133be 0x10603917a 0x10603f123 0x105d100b5 0x105d98f26 0x1059a37c4
libc++abi.dylib: terminating with uncaught exception of type kj::ExceptionImpl: src/kj/io.c++:259: failed: miniposix::read(fd, pos, max - pos): Bad file descriptor; fd = 3
```

**Comment by drakedevel** [comment] 2015-11-28 02:09
I just ran into this bug! The issue is that `read` and `read_packed` don't actually read the entire contents of the file eagerly -- they will read more data in as needed. The real bug is that pycapnp doesn't hold a reference to the file object you pass in, so it gets freed after the `read` call (closing the fd) and the underlying C++ object is left with a reference to a now-invalid file descriptor. As soon as a field is accessed past the end of the initial buffered read it will crash (or worse, read from a random subsequently-opened file). This is the relevant strace from my system:

```
open("data/tmp.cpn", O_RDONLY|O_CLOEXEC) = 7
fstat(7, {st_mode=S_IFREG|0644, st_size=24726, ...}) = 0
ioctl(7, TCGETS, 0x7ffcfcfbaf30)        = -1 ENOTTY (Inappropriate ioctl for device)
fstat(7, {st_mode=S_IFREG|0644, st_size=24726, ...}) = 0
lseek(7, 0, SEEK_CUR)                   = 0
ioctl(7, TCGETS, 0x7ffcfcfbae90)        = -1 ENOTTY (Inappropriate ioctl for device)
lseek(7, 0, SEEK_CUR)                   = 0
read(7, "\21\1\4\3\211\23@\1\21\1\17A\4\1\21\2\1q\1\2048\1\20\1\21\2\3\21\4\5\21\6"..., 8192) = 8192
close(7)                                = 0
read(7, 0x55d60d17eee0, 8192)           = -1 EBADF (Bad file descriptor)
```

The easiest workaround is to hold the file open while using the capnp objects. I modified your example, wrapping the body of `test_read` with `with open(FNAME, 'r') as f:` and the tests pass with arbitrarily large numbers.

**Closed** 2015-12-05 00:32 UTC

**Comment by jparyani** [comment] 2015-12-05 00:33
Sorry this took me so long to get to. I didn't deal with it right away and managed to forget about it.

Thanks for both of you reporting it!
